In [4]:
import numpy as np
import math
def sampleImages(images,patch,numbatch,imageNum):
    samples=np.zeros([patch*patch,1,imageNum*numbatch])
    for i in range(imageNum):
        rows=images[:,:,i].shape[0];cols=images[:,:,i].shape[1];
        for j in range(numbatch):
            row=np.random.randint(0,rows);
            col=np.random.randint(0,cols);
            samples[:,:,i*numbatch+j]=images[row:row+patch,col:col+patch,i].reshape(patch*patch,1)
    return samples
def normalize(samples):
    mean=np.mean(samples);
    samples=samples-mean;
    return samples
def initializeParameters(hiddenSize, visibleSize):
    r  = math.sqrt(6)
    w1=-r+2*r*np.random.rand(hiddenSize,visibleSize)
    w2=-r+2*r*np.random.rand(visibleSize,hiddenSize)
    b1=np.zeros([hiddenSize,1])
    b2=np.zeros([visibleSize,1])
    return [w1,w2,b1,b2]
def sparseAutoencoderCost(theta,visibleSize, hiddenSize,lambda1, sparsityParam, beta, data):
    w1=theta[0];w2=theta[1];b1=theta[2];b2=theta[3];
    w1gd=np.zeros(w1.shape)
    w2gd=np.zeros(w2.shape)
    b1gd=np.zeros(b1.shape)
    b2gd=np.zeros(b2.shape)
    #feedforward
    Jcost = 0;#直接误差
    Jweight = 0;#权值惩罚
    Jsparse = 0;#稀疏性惩罚
    (n,m)=data.shape
    b1=get_batch_bias(b1,m);b2=get_batch_bias(b2,m);
    z2=np.dot(w1,data)+b1;a2=sigmoid(z2);
    z3=np.dot(w2,a2)+b2;a3=sigmoid(z3);
    Jcost=0.5*np.sum(a3-data)/m
    Jweight=0.5*(np.sum(w1*w1)+np.sum(w2*w2))
    ap=np.mean(a2,axis=0)
    Jsparse=np.sum(sparsityParam*np.log(sparsityParam/ap)+(1-sparsityParam)*np.log((1-sparsityParam)/(1-ap)))
    cost=Jcost+Jweight*lambda1+Jsparse*beta
    #反向计算每个节点的误差值
    d3=-(a3-data)*sig_bg(z3)
    sparsegd=beta*(-sparsityParam/ap+(1-sparsityParam)/(1-ap))
    d2=(np.dot(w2.T,d3)+aparsegd)*sig_bg(z2)
    w2gd=np.dot(d3,a2.T)/m+lamda1*w2;
    w1gd=np.dot(d2,data.T)/m+lamda*w1;
    b2gd=np.mean(d3,axis=1)
    b1gd=np.mean(d2,axis=1)
    return [cost,w1gd,w2gd,b1gd,b2d]
def display_network(A, opt_normalize, opt_graycolor, cols, opt_colmajor):
    #This function visualizes filters in matrix A. Each column of A is a
    #filter. We will reshape each column into a square image and visualizes
# on each cell of the visualization panel. 
# All other parameters are optional, usually you do not need to worry
# about it.
# opt_normalize: whether we need to normalize the filter so that all of
#  them can have similar contrast. Default value is true.
#  opt_graycolor: whether we use gray as the heat map. Default is true.
#  cols: how many columns are there in the display. Default value is the
#  squareroot of the number of columns in A.
#  opt_colmajor: you can switch convention to row major for A. In that
#  case, each row of A is a filter. Default value is false.
    
def get_batch_bias(bias,m):
    n=bias.shape[0]
    res_bias=np.zeros([n,m])
    for i in range(m):
        res_bias[:,i]=bias.reshape(n,)
    return res_bias
def sigmoid(z):
    return 1/(1+np.exp(-z))
def sig_bg(z):
    return sigmoid(z)*(1-sigmoid(z))

In [13]:
a=(-6+12*np.random.rand(3,4))
a

array([[-3.86049303, -1.49458452, -1.1567575 , -5.68208473],
       [ 2.46208057,  3.28688327, -0.33799334, -3.53253527],
       [-3.90864514,  5.39617369, -1.19522164,  1.61537702]])

In [14]:
np.mean(a,axis=0)

array([-1.7690192 ,  2.39615748, -0.89665749, -2.53308099])

In [23]:
np.log(3/a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[        nan,         nan,         nan,         nan],
       [ 0.19760554, -0.09132749,         nan,         nan],
       [        nan, -0.58707784,         nan,  0.61904391]])