In [18]:
#function [f,g] = linear_regression(theta, X,y)
#functions=linear_regression(theta, X,y)#functions[0]=f,functions[1]=g
#   %
#   % Arguments:
#   %   theta - A vector containing the parameter values to optimize.
#   %   X - The examples stored in a matrix.
#   %       X(i,j) is the i'th coordinate of the j'th example.
#   %   y - The target value for each example.  y(j) is the target for example j.
#   %
def linear_regression(theta, X,y):
    m=X.shape[1];
    n=X.shape[0];

    f=0;
    g=np.zeros(theta.shape[0]);
    for i in range(0,m):
        temp=0
        for j in range(0,n):
            temp+=theta[j]*X[j,i]
        f+=0.5*(temp-y[i])**2
    for j in range(0,n): 
        for i in range(0,m):
            temp=0
            for k in range(0,n):
                temp+=theta[k]*X[k,i]
            g[j]+=(temp-y[i])*X[j,i]
    return [f,g]
#   %
#   % TODO:  Compute the linear regression objective by looping over the examples in X.
#   %        Store the objective function value in 'f'.
#   %
#   % TODO:  Compute the gradient of the objective with respect to theta by looping over
#   %        the examples in X and adding up the gradient for each example.  Store the
#   %        computed gradient in 'g'.
  
# %%% YOUR CODE HERE %%%
    

## linear_reg_vec

In [ ]:
function [f,g] = linear_regression_vec(theta, X,y)
#   %
#   % Arguments:
#   %   theta - A vector containing the parameter values to optimize.
#   %   X - The examples stored in a matrix.
#   %       X(i,j) is the i'th coordinate of the j'th example.
#   %   y - The target value for each example.  y(j) is the target for example j.
#   %
def linear_regression(theta, X,y):
    m=X.shape[1];
    n=X.shape[0];
    import numpy as np
    f=0;
    g=np.zeros(theta.shape[0]);
    cal_1=np.dot(theta,X)
    for i in range(0,m):
        f+=(theta[i]-y[i])**2
    f=f/2
    for j in range(0,n):
        g[j]=(cal_1-y)*X[j,:]
    return [f,g]

In [51]:
A=np.random.rand(10,1)
print(np.mean(A))
print(A)
print(A**2)

0.638830660214
[[ 0.48212484]
 [ 0.92605135]
 [ 0.56307703]
 [ 0.79008485]
 [ 0.45603593]
 [ 0.56143615]
 [ 0.42263137]
 [ 0.6478447 ]
 [ 0.94607792]
 [ 0.59294246]]
[[ 0.23244436]
 [ 0.85757111]
 [ 0.31705574]
 [ 0.62423407]
 [ 0.20796877]
 [ 0.31521055]
 [ 0.17861727]
 [ 0.41970275]
 [ 0.89506343]
 [ 0.35158076]]


## ex_linear_reg

In [ ]:
# %
# %This exercise uses a data from the UCI repository:
# % Bache, K. & Lichman, M. (2013). UCI Machine Learning Repository
# % http://archive.ics.uci.edu/ml
# % Irvine, CA: University of California, School of Information and Computer Science.
# %
# %Data created by:
# % Harrison, D. and Rubinfeld, D.L.
# % ''Hedonic prices and the demand for clean air''
# % J. Environ. Economics & Management, vol.5, 81-102, 1978.
# %
# addpath ../common
# addpath ../common/minFunc_2012/minFunc
# addpath ../common/minFunc_2012/minFunc/compiled

# % Load housing data from file.
data = load('housing.data');
cols=data.shape[1]
append=np.ones(shape=(1,cols))
# % Include a row of 1s as an additional intercept feature.
data = np.insert(data,0,values=append,axis=0)
# % Shuffle examples.
# data = data(:, randperm(size(data,2)));
data1=data.T
np.random.shuffle(data1)
data2=data1.T
# % Split into train and test sets
# % The last row of 'data' is the median home price.
train_X = data2[1:end-1,1:400];
train_y = data2[end,1:400];

test_X = data2[1:end-1,401:end];
test_y = data2[end,401:end];

m=train_X.shape(1);
n=train_X.shape(0);

# % Initialize the coefficient vector theta to random values.
theta=np.random.rand(n,1)
    
# % Run the minFunc optimizer with linear_regression.m as the objective.
# %
# % TODO:  Implement the linear regression objective and gradient computations
# % in linear_regression.m
# %
# tic;
# options = struct('MaxIter', 200);
# theta = minFunc(@linear_regression, theta, options, train.X, train.y);
# fprintf('Optimization took %f seconds.\n', toc);

# % Run minFunc with linear_regression_vec.m as the objective.
# %
# % TODO:  Implement linear regression in linear_regression_vec.m
# % using MATLAB's vectorization features to speed up your code.
# % Compare the running time for your linear_regression.m and
# % linear_regression_vec.m implementations.
# %
# % Uncomment the lines below to run your vectorized code.
# %Re-initialize parameters
# %theta = rand(n,1);
# %tic;
# %theta = minFunc(@linear_regression_vec, theta, options, train.X, train.y);
# %fprintf('Optimization took %f seconds.\n', toc);

# % Plot predicted prices and actual prices from training set.
def ex_linear_reg(theta,X,y,lr,epoches):
    res_theta=theta
    for i in range(epoches):
        [f,g]=linear_regression(theta,train_X,train_y)
        print("the cost is %f",f)
        theta-=lr*g
        if costmin>f:
            costmin=f
            res_theta=theta
    return res_theta
lr=0.05
epoches=5
costmin=1000   
res_theta=ex_linear_reg(theta,train_X,train_y,lr,epoches)
actual_prices = train_y;
predicted_prices =np.dot(res_theta,train_X) 

# % Print out root-mean-squared (RMS) training error.
train_rms=(np.mean((predicted_prices - actual_prices)**2))**0.5;
print('RMS training error: %f\n', train_rms);

# % Print out test RMS error
actual_prices = test_y;
predicted_prices = np.dot(res_theta,test_X) 
test_rms==(np.mean((predicted_prices - actual_prices)**2))**0.5;
print('RMS testing error: %f\n', test_rms);

# % Plot predictions on test data.
%matplotlib inline
import matplotlib.pyplot as plt
plt.plot(np.range(m-400),predicted_prices,'xg',label='predicted')
plt.plot(np.range(m-400),actual_prices,'*b',label='actual')
plt.legend()
plt.xlabel('House #')
plt.ylabel('House price')
# plot_prices=true;
# if (plot_prices)
#   [actual_prices,I] = sort(actual_prices);
#   predicted_prices=predicted_prices(I);
#   plot(actual_prices, 'rx');
#   hold on;
#   plot(predicted_prices,'bx');
#   legend('Actual Price', 'Predicted Price');
#   xlabel('House #');
#   ylabel('House price ($1000s)');
# end

In [43]:
arr=np.arange(12).reshape(3,4)
print(arr)
brr=arr.T
print(brr)
np.random.shuffle(brr)
print(brr)
print(brr.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 2  6 10]
 [ 1  5  9]
 [ 3  7 11]]
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


In [45]:
arr[1:2,1:]

array([[6, 5, 7]])

In [46]:
arr

array([[ 0,  2,  1,  3],
       [ 4,  6,  5,  7],
       [ 8, 10,  9, 11]])

In [12]:
import numpy as np
theta=np.array([1,2,3,4])
x=np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])
np.dot(theta,x)

array([34, 44, 54])

In [28]:
x.shape[1]

3

In [10]:
x[:,0]

array([1, 4, 7, 1])

In [30]:
np.ones(shape=(1,2))

array([[ 1.,  1.]])

In [16]:
theta*x[:,0]

array([ 1,  8, 21,  4])